package com.ccq.bangdream.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ccq.bangdream.pojo.Card;
import com.ccq.bangdream.pojo.Panel;

import com.ccq.bangdream.greendao.CardDao;
import com.ccq.bangdream.greendao.PanelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardDaoConfig;
    private final DaoConfig panelDaoConfig;

    private final CardDao cardDao;
    private final PanelDao panelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        panelDaoConfig = daoConfigMap.get(PanelDao.class).clone();
        panelDaoConfig.initIdentityScope(type);

        cardDao = new CardDao(cardDaoConfig, this);
        panelDao = new PanelDao(panelDaoConfig, this);

        registerDao(Card.class, cardDao);
        registerDao(Panel.class, panelDao);
    }

    public void clear() {
        cardDaoConfig.clearIdentityScope();
        panelDaoConfig.clearIdentityScope();
    }

    public CardDao getCardDao() {
        return cardDao;
    }

    public PanelDao getPanelDao() {
        return panelDao;
    }

}
